### ISSUE TITLE
使用 Docker 打造超溜的前端环境

### ISSUE THREAD

**Issue by axetroy** [axetroy/blog#178]
#### 前言:

> 没有什么是非得用 xx 技术才行的，只是 **能用** 和 **好用** 的区别
> 有写习惯了老旧的工作方式，不愿去学习，不愿意去改变，追求 “能用就行”
> 有些不单追求能用，还有提升的空间，追去好用
> It's up to you!

### 为什么需要 Docker?

在上一家公司，操作系统是自由的，你想用 Windows/Linux/Mac, 只要你用的习惯，能够高效率工作，无所谓什么系统。

然而问题就来了，大家的环境不一样。Unix 系系统基本无太大差别，Windows 就不一样了。环境的差异会导致踩很多很多坑, 印象比较深刻的就是 sass 编译，在哪个还需要依赖 ruby 的年代，安装 gem 是不顺畅的，windows 格式编码格式不是 utf-8, 导致 sass 文件中有中文编译报错等等。还有一些诸如文件监听，在 Windows 下需要 fallback，靠轮循监听变化。

在经过一系列的折腾之后，我们就尝试使用 Docker 来解决开发环境统一的问题。

构建一个通用的 Linux 镜像，里面包含了前端开发的基本环境，包括 python，nodejs 等等... 前端只要给定源码文件就行了。就这样暂时统一了开发环境，虽然最后我们统一使用 Unix 系统。

### Docker 还有哪些场景

**假设是前后端不分离的项目**

你作为一个前端，你是如何与 PHP 后端参与开发的？你需要搭建 PHP 环境吗？

> 我不搭建 PHP 开发环境，FTP 直接上传，就是这么简单粗暴，Docker 什么的，能吃吗 ∂？

如果你是这种开发模式，不是说 low，而是说效率低下。每次修改都要上传，盲人改代码。

所以你需要 Docker，配置好环境，一键启动，一键关闭，各开发人员相互独立，代码通过 git 同步，指向同一个数据库，修改代码立即见效，`F*CK FTP`

**假设是前后端分离的单页面应用**

前后端分离的情况下，单页面渲染一般使用`nginx`, Docker 同样配置 nginx，做静态页渲染和去除难看的`#`号(通过 404 重定向只 index.html, 把 404 的控制权，交换给前端)

这样你的路由`http://example.com/#/home`变成了`http://example.com/home`

甚至你可以作反向代理，消除跨域

`http://example.com/api` > `http://api.server.com`

**假设是前后端分离服务端渲染应用**

那么你更需要 Docker, 因为你需要 Node 环境，你需要负载均衡，你需要反向代理等等...

### 如何应用 Docker

首先你得安装`Docker` 和 `Docker Compose`, 使用 `Docker Compose`来配置镜像.

#### 配置最简单的 Node 环境

一个简单的项目结构如下

```
├── docker-compose.yml
└── index.js
```

```javascript
// index.js
const http = require('http');

const server = http.createServer((req, res) => {
  res.setHeader('Content-Type', 'text/html');
  res.setHeader('X-Foo', 'bar');
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.end('ok');
});

server.listen(3000);
```

```yml
# docker-compose.yml

version: "3"
services:
  web:
    image: node:8-alpine
    user: node
    working_dir: /home/node/app
    environment:
      - PORT=3000
    volumes:
      - ./:/home/node/app # 将本地目录映射到容器内
    command: ["node", "index.js"] # 运行命令
    ports:
      - 3000:3000 # 本地端口:容器端口
```

运行命令启动

```bash
$ docker-compose up
Starting example_web_1 ... done
Attaching to example_web_1
```

现在 NodeJs 应用已经跑起来了

#### Node 的依赖包怎么办?

现在我们给项目添加依赖`Koa`，用 Koa 来搭建服务器.

这我们需要把`node_modules`和`package.json`打包进镜像

而官方的 node 镜像`node:8-alpine`是不安装依赖的，需要我们自定义一个镜像

创建一个 `Dockerfile`

```dockerfile
FROM node:8-alpine

# 设置工作目录
WORKDIR /home/node/app

# 把package.json复制进镜像中
COPY ./package.json /home/node/app/package.json

# 在镜像中安装依赖
RUN yarn --production
```

修改 `docker-compose.yml`

```yml
# docker-compose.yml

version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: node
    working_dir: /home/node/app
    environment:
      - PORT=3000
    volumes:
      - ./index.js:/home/node/app/index.js # 将本地目录映射到容器内
    command: ["node", "index.js"] # 运行命令
    ports:
      - 3000:3000 # 本地端口:容器端口
```

此时项目目录

```
├── Dockerfile
├── docker-compose.yml
├── index.js
├── package.json
└── yarn.lock
```

运行命令

```bash
$ docker-compose up
Building web
Step 1/5 : FROM node:8-alpine
 ---> 86b71ddd55fa
Step 2/5 : WORKDIR /home/node/app
 ---> Using cache
 ---> 2347fe6d8f3c
Step 3/5 : COPY ./package.json /home/node/app/package.json
 ---> Using cache
 ---> 1e0026f493f5
Step 4/5 : RUN yarn --production
 ---> Using cache
 ---> 549284f78c1c
Step 5/5 : RUN ls ./node_modules
 ---> Using cache
 ---> 350adf90cfa8
Successfully built 350adf90cfa8
Successfully tagged example_web:latest
Recreating example_web_1 ... done
Attaching to example_web_1
```

服务已运行起来了，访问 3000 试试看吧

#### 如何用 Nginx 反向代理，消除跨域问题

首先得有一个 nginx.conf 配置

```conf
# nginx.conf
user nginx;
worker_processes 1;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
	worker_connections 1024;
}


http {

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
	'$status $body_bytes_sent "$http_referer" '
	'"$http_user_agent" "$http_x_forwarded_for"';

	access_log /var/log/nginx/access.log main;

	sendfile on;
	tcp_nopush on;

	gzip on;

	# 定义上游服务器
	upstream api {

		ip_hash;

		server koaserver:3000 weight=1;

		keepalive 300;
	}

	server {

		listen 80;
		server_name localhost;

		charset utf-8;

		root   /usr/share/nginx/html;

		# 代理以 api 为前缀的请求
		location ~^/api {
			proxy_pass http://api;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
		}

		error_page 500 502 503 504 /50x.html;

		location = /50x.html {
			root /usr/share/nginx/html;
		}
	}

}
```

```yml
version: "3"
services:
  nginx_proxy:
    image: nginx:1.13.8-alpine
    restart: always
    working_dir: /home/static
    volumes:
       - ./index.html:/usr/share/nginx/html/index.html
       - ./nginx.conf:/etc/nginx/nginx.conf # 映射 ginx 配置文件
    ports:
      - 3000:80 # 绑定容器的80端口到本的1080端口
    links:
      - web:koaserver # 给它取个别名，叫做 koaserver
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: node
    working_dir: /home/node/app
    environment:
      - PORT=3000
    volumes:
      - ./index.js:/home/node/app/index.js # 将本地目录映射到容器内
    command: ["node", "index.js"] # 运行命令
```

此时项目目录

```
├── Dockerfile
├── docker-compose.yml
├── index.html
├── index.js
├── nginx.conf
├── package.json
└── yarn.lock
```

运行命令

```bash

```

访问 `localhost:3000`， 返回 `hello html`
访问 `localhost:3000/api`， 返回 `hello koa`

解决跨域问题，但同时也存在问题，代理之后，应用程序无法获取 IP，需要从 header 的`X-Real-IP`
字段获取

### 最佳部署姿势是怎么样的?

其他还有很多案例需要使用 Docker，特别是开发后端的应用。后端应用依赖 数据库(MySQL, Postgres, Redis...)、服务器(Nginx/Apache)，开发语言(如 PHP)。

如果我是一名开发者，接手别人的项目，项目需要安装 PHP6.5, 需要安装 MySQL@xxx, Apache@xxx， redix@xxx. 最好能提供一个`docker-compose.yml`，否则我不保证我打不死你

回到 Node 部署，最佳的姿势应该是把`编译过后的代码(例如Typescript>JS)+依赖+配置`打包进镜像，然后 push 镜像，最后在服务端部署。其余的配置，尽量都通过`docker-compose.yml`的环境变量去设置

**做到只需要一个配置文件，就能把完整的项目搭建起来**
